spring:
  application:
    name: orchestrator-engine
    version: 0.0.7

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

server:
  port: ${SERVER_PORT:8000}

grpc:
  server:
    port: ${GRPC_PORT:8100}

logging:
  level:
    root: ${LOG_LEVEL:INFO}